# Runtime settings used by the SF32LB52 LVGL examples.
CONFIG_RT_MAIN_THREAD_STACK_SIZE=4096
CONFIG_RT_MAIN_THREAD_PRIORITY=19
CONFIG_RT_TIMER_THREAD_STACK_SIZE=1024
CONFIG_RT_USING_ULOG=y
CONFIG_RT_USING_MEMHEAP=y
CONFIG_RT_USING_MEMTRACE=y
CONFIG_BSP_USING_FULL_ASSERT=y

# LCD: CO5300 1.85" 390x450 QSPI
CONFIG_BSP_USING_LCD=y
CONFIG_LCD_USING_TFT_CO5300=y
CONFIG_BSP_USING_TOUCHD=y

# LVGL V8
CONFIG_PKG_USING_LITTLEVGL2RTT=y
CONFIG_LVGL_V8=y
# CONFIG_LV_USING_EXT_RESOURCE_MANAGER is not set
CONFIG_LV_INDEV_DEF_READ_PERIOD=16
CONFIG_LV_IMG_CACHE_DEF_SIZE=16
CONFIG_LV_FB_ONE_NOT_SCREEN_SIZE=y
CONFIG_LV_FB_LINE_NUM=100
CONFIG_LCD_FB_USING_AUTO=y
CONFIG_LV_RES_AUTO=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_USE_PERF_MONITOR=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_FONT_MONTSERRAT_28=y
CONFIG_LV_FONT_MONTSERRAT_36=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16=y

# Board peripherals
CONFIG_LXT_DISABLE=y
